version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: djangoadmin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
  server:
    build:
      context: {config.server_dir}
    entrypoint: /bin/bash -c
    ports:
      - "8000:8000"
    depends_on:
      - db
    image: python:3-onbuild
    environment:
      DB_USER: djangoadmin
      DB_PASSWORD: password
  web:
    build:
      context: {config.web_dir}
    entrypoint: /bin/bash -c
    image: node:8.11.2-onbuild
    ports:
      - "3000:3000"
    depends_on:
      - server